SCREEN_WIDTH = 550
SCREEN_HEIGHT = 680

NUMBER_OF_BLOCKS_ROW = 9
NUMBER_OF_BLOCKS_COL = 9
BLOCK_WIDTH = round(SCREEN_WIDTH / NUMBER_OF_BLOCKS_COL / 1.2)
BLOCK_HEIGHT = BLOCK_WIDTH
SIDE_SPACE = round((SCREEN_WIDTH - BLOCK_WIDTH*NUMBER_OF_BLOCKS_ROW) / 2)
TOP_SPACE = round((SCREEN_HEIGHT - BLOCK_HEIGHT*NUMBER_OF_BLOCKS_COL) / 3.5) # 2.7
MENU_SPACE = round((SCREEN_HEIGHT - BLOCK_HEIGHT*NUMBER_OF_BLOCKS_COL) / 6.7)

LIGHT_BLUE = (15, 165, 255)
LIGHTER_BLUE = (150, 214, 255)
BACK_BLUE = (15, 165, 255)
GREY = (150, 150, 150)
LIGHT_GREY = (200, 200, 200)
BLACK = (0, 0, 0)

#global SET_HIGHLIGHT
#SET_HIGHLIGHT = [0, 0]

GAME_FILE = 'prepped_games/prepped_games_file.txt'
GAME_FILE_SOLVED = 'prepped_games/prepped_games_file_solved.txt'
GAME_ICON = 'img/icon1.png'
GAME_TITLE = 'SUDOKU SOLVER'



